export default function getCommands() {
    return [
        { cmd: 'imp', desc: 'Implieds (updated every few minutes, Mon-Fri)', category: 'Market Data' },
        // { cmd: 'graph', desc: 'Generate graph', category: 'Tools' },
        // { cmd: 'rain', desc: 'Rain data', category: 'Weather' },
        // { cmd: 'vwap', desc: 'VWAP', category: 'Market Data' },
        { cmd: 'markets', desc: 'Quick overview of the markets', category: 'Market Data' },
        { cmd: 'fx', desc: 'Recent FX rates for major currencies', category: 'Market Data' },
        { cmd: 'wasde', desc: 'WASDE report summary vs estimates', category: 'Reports' },
        { cmd: 'nopa', desc: 'NOPA Net Crush and SoyOil Stock report', category: 'Reports' },
        { cmd: 'cbotfm', desc: 'CBOT Fund Movements', category: 'Market Data' },
        { cmd: 'cecrep', desc: 'Most recent CEC Report Figures', category: 'Reports' },
        { cmd: 'sagispro', desc: 'SAGIS Monthly - Processed', category: 'Reports' },
        { cmd: 'sagisdel', desc: 'SAGIS Monthly - Deliveries', category: 'Reports' },
        { cmd: 'sbdel', desc: 'Soybeans Weekly Producer Deliveries SA', category: 'Deliveries' },
        { cmd: 'sfdel', desc: 'Sunflower Seed Weekly Producer Deliveries SA', category: 'Deliveries' },
        { cmd: 'wedel', desc: 'Wheat Weekly Producer Deliveries SA', category: 'Deliveries' },
        { cmd: 'wmdel', desc: 'White Maize Weekly Producer Deliveries SA', category: 'Deliveries' },
        { cmd: 'ymdel', desc: 'Yellow Maize Weekly Producer Deliveries SA', category: 'Deliveries' },
        { cmd: 'uscrop', desc: 'US Crop Progress and Condition', category: 'Reports' },
        { cmd: 'cbot', desc: 'CBOT Current Prices', category: 'Prices' },
        { cmd: 'oio', desc: 'Open Interest Oilseeds', category: 'Market Data' },
        { cmd: 'oig', desc: 'Open Interest Grains', category: 'Market Data' },
        { cmd: 'mtmo', desc: 'Mark to Market Oilseeds', category: 'Market Data' },
        { cmd: 'mtmg', desc: 'Mark to Market Grains', category: 'Market Data' },
        { cmd: 'qgs', desc: 'Quarterly Grain Stocks', category: 'Reports' },
        { cmd: 'spreadsoya', desc: 'Last Trade on SOYA Spread', category: 'Spreads' },
        { cmd: 'spreadsuns', desc: 'Last Trade on SUNS Spread', category: 'Spreads' },
        { cmd: 'spreadweat', desc: 'Last Trade on WEAT Spread', category: 'Spreads' },
        { cmd: 'spreadymaz', desc: 'Last Trade on YMAZ Spread', category: 'Spreads' },
        { cmd: 'spreadwmaz', desc: 'Last Trade on WMAZ Spread', category: 'Spreads' },
        { cmd: 'weat', desc: 'Last Trade on WEAT Futures', category: 'Futures' },
        { cmd: 'soya', desc: 'Last Trade on SOYA Futures', category: 'Futures' },
        { cmd: 'suns', desc: 'Last Trade on SUNS Futures', category: 'Futures' },
        { cmd: 'wmaz', desc: 'Last Trade on WMAZ Futures', category: 'Futures' },
        { cmd: 'ymaz', desc: 'Last Trade on YMAZ Futures', category: 'Futures' },
        { cmd: 'ipa', desc: 'Import Parities', category: 'Parities' },
        { cmd: 'xpa', desc: 'Export Parities', category: 'Parities' },
    ];
}